name: Build .NET Framework 4.7 Library

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: windows-latest

    env:
      Solution_Name: Codesandbox.SDK.Net.sln  # Adjust if your solution file is named differently

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Restore NuGet packages
      run: nuget restore ${{ env.Solution_Name }}

    - name: Build solution
      run: msbuild ${{ env.Solution_Name }} /p:Configuration=Release
