jobs:
  build:
    runs-on: windows-latest

    env:
      Solution_Name: Codesandbox.SDK.Net.sln

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Cache NuGet packages
      uses: actions/cache@v3
      with:
        path: packages
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.config') }}
        restore-keys: |
          ${{ runner.os }}-nuget-

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Restore NuGet packages
      run: nuget restore ${{ env.Solution_Name }}

    - name: List restored packages
      run: dir packages /s /b

    - name: Build solution
      run: msbuild ${{ env.Solution_Name }} /p:Configuration=Release
